/**
 * PERFECT PROTECTION SECURITY AGENCY - DATA STORE & REPOSITORY
 * Final Year Project 2026 - Security & Housekeeping Staff Management System
 * 
 * Provides mock relational dataset and LocalStorage synchronization
 * aligned with Java Spring Boot backend entities and MySQL database.
 */

const PPSA_STORAGE_KEY = 'PPSA_ENTERPRISE_DATA_2026_V1';

const INITIAL_PPSA_DATA = {
  // Organizations / Institutions
  organizations: [
    {
      id: 'ORG-1001',
      name: 'Government Higher Secondary School',
      type: 'Government School',
      contactPerson: 'Dr. Rajesh Sen (Principal)',
      phone: '9876543210',
      email: 'principal.ghss@gov.in',
      address: 'Sector 4, Civil Lines',
      city: 'Capital City',
      state: 'Maharashtra',
      pincode: '400001',
      requiredStaff: 4,
      assignedStaff: 4,
      status: 'Active',
      createdDate: '2026-08-15'
    },
    {
      id: 'ORG-1002',
      name: 'District Collectorate & Revenue Complex',
      type: 'Government Office',
      contactPerson: 'Vinod Meena (Administrative Officer)',
      phone: '9822012345',
      email: 'collectorate.admin@gov.in',
      address: 'Collectorate Road, Civil Administrative Zone',
      city: 'Capital City',
      state: 'Maharashtra',
      pincode: '400002',
      requiredStaff: 8,
      assignedStaff: 8,
      status: 'Active',
      createdDate: '2026-08-20'
    },
    {
      id: 'ORG-1003',
      name: 'Civil General District Hospital',
      type: 'Hospital',
      contactPerson: 'Dr. Meenakshi Iyer (Medical Supt.)',
      phone: '9845098765',
      email: 'civilhosp.admin@healthgov.in',
      address: 'Main Health City Complex, MG Road',
      city: 'Capital City',
      state: 'Maharashtra',
      pincode: '400008',
      requiredStaff: 12,
      assignedStaff: 10,
      status: 'Active',
      createdDate: '2026-09-01'
    },
    {
      id: 'ORG-1004',
      name: 'State Institute of Technology & Engineering',
      type: 'College',
      contactPerson: 'Prof. Anil Kulkarni (Dean Facilities)',
      phone: '9811223344',
      email: 'dean.site@edu.ac.in',
      address: 'University Ring Road Campus',
      city: 'Capital City',
      state: 'Maharashtra',
      pincode: '400015',
      requiredStaff: 6,
      assignedStaff: 6,
      status: 'Active',
      createdDate: '2026-09-05'
    },
    {
      id: 'ORG-1005',
      name: 'Precision Auto-Tech Industrial Plant',
      type: 'Factory',
      contactPerson: 'Harish Rao (Plant Security Head)',
      phone: '9870192837',
      email: 'h.rao@precisionautotech.com',
      address: 'MIDC Industrial Sector, Plot 42-A',
      city: 'Capital City',
      state: 'Maharashtra',
      pincode: '400065',
      requiredStaff: 10,
      assignedStaff: 6,
      status: 'Active',
      createdDate: '2026-09-12'
    },
    {
      id: 'ORG-1006',
      name: 'Municipal Corporation Head Office',
      type: 'Government Office',
      contactPerson: 'Sunita Patil (Deputy Commissioner)',
      phone: '9833445566',
      email: 'mc.headoffice@gov.in',
      address: 'Central Civic Tower, Ambedkar Chowk',
      city: 'Capital City',
      state: 'Maharashtra',
      pincode: '400001',
      requiredStaff: 5,
      assignedStaff: 0,
      status: 'Pending Assignment',
      createdDate: '2026-09-26'
    }
  ],

  // Security Staff Roster
  securityStaff: [
    {
      id: 'SEC-101',
      name: 'Ramesh Kumar',
      phone: '9876012345',
      address: 'B-14 Shanti Nagar, Capital City',
      designation: 'Senior Security Guard',
      joiningDate: '2023-03-15',
      experience: '6 Years',
      qualification: 'Ex-Military Service (8 Yrs) / 12th Standard',
      skills: 'Armed Security, Perimeter Vigil, CCTV Monitoring',
      shiftPreference: 'Morning',
      assignedOrgId: 'ORG-1001',
      assignedOrgName: 'Government Higher Secondary School',
      status: 'Active',
      badgeNumber: 'PP-SG-01'
    },
    {
      id: 'SEC-102',
      name: 'Mahendra Pratap Singh',
      phone: '9876023456',
      address: '45 Defense Enclave, Capital City',
      designation: 'Security Supervisor',
      joiningDate: '2022-01-10',
      experience: '9 Years',
      qualification: 'Bachelor of Arts / NCC "C" Certificate',
      skills: 'Workforce Roster, Crisis Response, Fire Drill Coordination',
      shiftPreference: 'Morning',
      assignedOrgId: 'ORG-1002',
      assignedOrgName: 'District Collectorate & Revenue Complex',
      status: 'Active',
      badgeNumber: 'PP-SS-01'
    },
    {
      id: 'SEC-103',
      name: 'Vikram Jadhav',
      phone: '9876034567',
      address: 'Plot 88 Shivaji Park, Capital City',
      designation: 'Security Guard',
      joiningDate: '2024-04-12',
      experience: '4 Years',
      qualification: '10th Standard / Certified Guard PSARA',
      skills: 'Access Control, Metal Detector Operation, Night Patrol',
      shiftPreference: 'Night',
      assignedOrgId: 'ORG-1003',
      assignedOrgName: 'Civil General District Hospital',
      status: 'Active',
      badgeNumber: 'PP-SG-02'
    },
    {
      id: 'SEC-104',
      name: 'Ajay Verma',
      phone: '9876045678',
      address: '22 Guru Gobind Society, Capital City',
      designation: 'Security Officer',
      joiningDate: '2021-08-01',
      experience: '8 Years',
      qualification: 'Diploma in Industrial Safety & Security',
      skills: 'VIP Protocol, Emergency Evacuation, Incident Logging',
      shiftPreference: 'Rotational',
      assignedOrgId: 'ORG-1002',
      assignedOrgName: 'District Collectorate & Revenue Complex',
      status: 'Active',
      badgeNumber: 'PP-SO-01'
    },
    {
      id: 'SEC-105',
      name: 'Manoj Tiwari',
      phone: '9876056789',
      address: '102 Shastri Nagar, Capital City',
      designation: 'Security Guard',
      joiningDate: '2024-11-20',
      experience: '3 Years',
      qualification: '12th Standard',
      skills: 'Student Discipline, Gate Register, Crowd Management',
      shiftPreference: 'Morning',
      assignedOrgId: 'ORG-1004',
      assignedOrgName: 'State Institute of Technology & Engineering',
      status: 'Active',
      badgeNumber: 'PP-SG-03'
    },
    {
      id: 'SEC-106',
      name: 'Suresh Yadav',
      phone: '9876067890',
      address: 'Sector 9 Industrial Colony, Capital City',
      designation: 'Security Guard',
      joiningDate: '2023-06-18',
      experience: '5 Years',
      qualification: '12th Standard',
      skills: 'Heavy Vehicle Check, Material Pass Verification',
      shiftPreference: 'Evening',
      assignedOrgId: 'ORG-1005',
      assignedOrgName: 'Precision Auto-Tech Industrial Plant',
      status: 'Active',
      badgeNumber: 'PP-SG-04'
    },
    {
      id: 'SEC-107',
      name: 'Dinesh Choudhary',
      phone: '9876078901',
      address: '77 Rajiv Gandhi Colony, Capital City',
      designation: 'Security Guard',
      joiningDate: '2025-02-14',
      experience: '2 Years',
      qualification: '10th Standard Pass',
      skills: 'Physical Fitness, Entry Screening, Radio Comms',
      shiftPreference: 'Morning',
      assignedOrgId: null,
      assignedOrgName: 'Unassigned (Available)',
      status: 'Active',
      badgeNumber: 'PP-SG-05'
    },
    {
      id: 'SEC-108',
      name: 'Balram Pandey',
      phone: '9876089012',
      address: '12 Subhash Nagar, Capital City',
      designation: 'Security Supervisor',
      joiningDate: '2022-09-01',
      experience: '7 Years',
      qualification: 'Graduate in Commerce',
      skills: 'Team Leadership, Shift Scheduling, Incident Reporting',
      shiftPreference: 'Rotational',
      assignedOrgId: null,
      assignedOrgName: 'Unassigned (Available)',
      status: 'Active',
      badgeNumber: 'PP-SS-02'
    }
  ],

  // Housekeeping Staff Roster
  housekeepingStaff: [
    {
      id: 'HK-201',
      name: 'Sunita Sharma',
      phone: '9867011223',
      address: 'H-33 Vikas Nagar, Capital City',
      designation: 'Cleaning Supervisor',
      joiningDate: '2022-05-10',
      experience: '7 Years',
      qualification: '10th Standard / Housekeeping Certification',
      skills: 'Chemical Dilution Protocol, Sanitization Audit, Hospital Hygiene',
      shiftPreference: 'Morning',
      assignedOrgId: 'ORG-1003',
      assignedOrgName: 'Civil General District Hospital',
      status: 'Active',
      badgeNumber: 'PP-HS-01'
    },
    {
      id: 'HK-202',
      name: 'Rekha Devi',
      phone: '9867022334',
      address: '89 Valmiki Basti, Capital City',
      designation: 'Sanitation Staff',
      joiningDate: '2023-09-14',
      experience: '4 Years',
      qualification: '8th Standard',
      skills: 'Bio-Medical Waste Segregation, Disinfection Fogging',
      shiftPreference: 'Morning',
      assignedOrgId: 'ORG-1003',
      assignedOrgName: 'Civil General District Hospital',
      status: 'Active',
      badgeNumber: 'PP-HK-01'
    },
    {
      id: 'HK-203',
      name: 'Govind Narang',
      phone: '9867033445',
      address: '12 Railway Line Colony, Capital City',
      designation: 'Office Cleaning Staff',
      joiningDate: '2023-02-18',
      experience: '5 Years',
      qualification: '10th Standard',
      skills: 'Mechanized Floor Scrubbing, Glass Facade Cleaning',
      shiftPreference: 'Evening',
      assignedOrgId: 'ORG-1002',
      assignedOrgName: 'District Collectorate & Revenue Complex',
      status: 'Active',
      badgeNumber: 'PP-HK-02'
    },
    {
      id: 'HK-204',
      name: 'Anita Kamble',
      phone: '9867044556',
      address: '44 Samata Nagar, Capital City',
      designation: 'School Cleaning Staff',
      joiningDate: '2024-01-08',
      experience: '3 Years',
      qualification: '8th Standard',
      skills: 'Classroom Sanitization, Restroom Hygiene, Playground Sweep',
      shiftPreference: 'Morning',
      assignedOrgId: 'ORG-1001',
      assignedOrgName: 'Government Higher Secondary School',
      status: 'Active',
      badgeNumber: 'PP-HK-03'
    },
    {
      id: 'HK-205',
      name: 'Raju Chauhan',
      phone: '9867055667',
      address: 'Plot 3 Azad Nagar, Capital City',
      designation: 'Facility Support Staff',
      joiningDate: '2022-11-25',
      experience: '6 Years',
      qualification: '10th Standard Pass',
      skills: 'Heavy Lifting, Waste Management, Campus Maintenance',
      shiftPreference: 'Full Day',
      assignedOrgId: 'ORG-1004',
      assignedOrgName: 'State Institute of Technology & Engineering',
      status: 'Active',
      badgeNumber: 'PP-HK-04'
    },
    {
      id: 'HK-206',
      name: 'Lakshmi Bai',
      phone: '9867066778',
      address: '18 Gandhi Nagar, Capital City',
      designation: 'Housekeeping Staff',
      joiningDate: '2024-06-01',
      experience: '4 Years',
      qualification: '8th Standard',
      skills: 'Wet Mopping, Eco-Friendly Cleaning, Surface Sterilization',
      shiftPreference: 'Morning',
      assignedOrgId: null,
      assignedOrgName: 'Unassigned (Available)',
      status: 'Active',
      badgeNumber: 'PP-HK-05'
    },
    {
      id: 'HK-207',
      name: 'Pappu Kumar',
      phone: '9867077889',
      address: '55 Indra Nagar, Capital City',
      designation: 'Sanitation Staff',
      joiningDate: '2025-01-15',
      experience: '2 Years',
      qualification: '10th Standard',
      skills: 'Drainage Care, Garbage Compactor, High-Pressure Washing',
      shiftPreference: 'Evening',
      assignedOrgId: null,
      assignedOrgName: 'Unassigned (Available)',
      status: 'Active',
      badgeNumber: 'PP-HK-06'
    }
  ],

  // Service Catalogue
  services: [
    {
      id: 'SRV-101',
      name: 'School Security Guard Service',
      category: 'Security',
      type: 'Security',
      description: 'Disciplined uniformed security staff trained for school main-gate vigilance, student entry/exit logging, visitor screening and boundary protection.',
      responsibilities: 'Gate access control, student safety vigil, visitor pass verification, emergency protocol coordination.',
      availableShifts: 'Morning, Full Day',
      minimumStaff: 2,
      durationOptions: '6 Months, 1 Year, 3 Years Contract',
      availability: 'Available Immediate',
      status: 'Active'
    },
    {
      id: 'SRV-102',
      name: 'Government Office Security',
      category: 'Security',
      type: 'Security',
      description: 'Institutional security team for government administrative complexes, ministry offices, collectorates and municipal boards.',
      responsibilities: 'File movement registry, vehicle screening, official record room security, crowd management at public counters.',
      availableShifts: 'Morning, Evening, Full Day, Rotational',
      minimumStaff: 4,
      durationOptions: 'Annual Government Tender / Contract',
      availability: 'Available Immediate',
      status: 'Active'
    },
    {
      id: 'SRV-103',
      name: 'Hospital & Healthcare Security',
      category: 'Security',
      type: 'Security',
      description: 'Specialized 24/7 security for emergency wards, casualty zones, ICU corridors, and doctor protection squads.',
      responsibilities: 'Emergency ward conflict de-escalation, visitor pass checks, parking regulation, medical staff escort.',
      availableShifts: 'Morning, Evening, Night, Rotational (24/7)',
      minimumStaff: 6,
      durationOptions: '12 Months to 36 Months',
      availability: 'Available Immediate',
      status: 'Active'
    },
    {
      id: 'SRV-104',
      name: 'Factory & Industrial Security',
      category: 'Security',
      type: 'Security',
      description: 'Tough industrial security personnel skilled in material inward/outward registers, weighbridge checking, and raw material theft prevention.',
      responsibilities: 'Truck inspection, employee biometric oversight, inventory security, fire safety patrols.',
      availableShifts: 'Rotational, 12-Hour Shifts, Night',
      minimumStaff: 4,
      durationOptions: '12 Months Contract',
      availability: 'Available Immediate',
      status: 'Active'
    },
    {
      id: 'SRV-201',
      name: 'Institutional Housekeeping & Cleaning',
      category: 'Housekeeping',
      type: 'Housekeeping',
      description: 'Comprehensive mechanized floor scrubbing, dusting, restroom sanitization and environmental upkeep for schools & campuses.',
      responsibilities: 'Classroom daily cleaning, drinking water cooler sanitization, waste segregation, corridor maintenance.',
      availableShifts: 'Morning, Evening',
      minimumStaff: 2,
      durationOptions: 'Annual Contract',
      availability: 'Available Immediate',
      status: 'Active'
    },
    {
      id: 'SRV-202',
      name: 'Government Office Deep Cleaning & Support',
      category: 'Housekeeping',
      type: 'Housekeeping',
      description: 'Professional cleaning of administrative desks, conference rooms, record storage halls, and high-footfall public lobbies.',
      responsibilities: 'Morning pre-office cleaning, sanitized restrooms, waste paper disposal, pantry hygiene support.',
      availableShifts: 'Morning, Evening, Full Day',
      minimumStaff: 3,
      durationOptions: 'Contract Basis',
      availability: 'Available Immediate',
      status: 'Active'
    },
    {
      id: 'SRV-203',
      name: 'Hospital Clinical Sanitation & Waste Management',
      category: 'Housekeeping',
      type: 'Housekeeping',
      description: 'Infection control hygiene squad trained in NABH healthcare protocols, yellow/red/blue bag bio-medical disposal.',
      responsibilities: 'Operation theatre sterilizing support, patient bed sanitization, biohazard disinfection fogging.',
      availableShifts: 'Round the Clock (3 Shifts)',
      minimumStaff: 6,
      durationOptions: '12 Months to 24 Months',
      availability: 'Available Immediate',
      status: 'Active'
    },
    {
      id: 'SRV-204',
      name: 'Facility Support & Maintenance Assistance',
      category: 'Housekeeping',
      type: 'Housekeeping',
      description: 'Handyman support, campus gardening, water pump operation, furniture shifting and general institution utility care.',
      responsibilities: 'Internal mail/file dispatch, light bulb replacement assistance, utility upkeep, recycling transport.',
      availableShifts: 'General Full Day (9 AM - 6 PM)',
      minimumStaff: 2,
      durationOptions: 'Annual Basis',
      availability: 'Available Immediate',
      status: 'Active'
    }
  ],

  // Service Requests (Bookings)
  serviceRequests: [
    {
      id: 'REQ-2026-1001',
      organizationName: 'Government Higher Secondary School',
      organizationType: 'Government School',
      serviceId: 'SRV-101',
      serviceName: 'School Security Guard Service',
      securityGuards: 2,
      supervisors: 0,
      housekeepingStaff: 2,
      totalStaff: 4,
      shift: 'Morning',
      startDate: '2026-10-01',
      duration: '12 Months',
      workingDays: 'Monday to Saturday',
      contactPerson: 'Dr. Rajesh Sen',
      email: 'principal.ghss@gov.in',
      phone: '9876543210',
      address: 'Sector 4, Civil Lines, Capital City',
      specialInstructions: 'Staff must arrive at 07:30 AM before school bell.',
      status: 'Staff Assigned', // Pending -> Under Review -> Approved -> Staff Assigned -> Active -> Completed
      requestDate: '2026-09-20'
    },
    {
      id: 'REQ-2026-1002',
      organizationName: 'District Collectorate & Revenue Complex',
      organizationType: 'Government Office',
      serviceId: 'SRV-102',
      serviceName: 'Government Office Security',
      securityGuards: 4,
      supervisors: 1,
      housekeepingStaff: 3,
      totalStaff: 8,
      shift: 'Full Day',
      startDate: '2026-10-05',
      duration: '24 Months',
      workingDays: 'All 7 Days',
      contactPerson: 'Vinod Meena',
      email: 'collectorate.admin@gov.in',
      phone: '9822012345',
      address: 'Collectorate Road, Civil Administrative Zone',
      specialInstructions: 'Official gate pass register mandatory for all visitors.',
      status: 'Active',
      requestDate: '2026-09-22'
    },
    {
      id: 'REQ-2026-1003',
      organizationName: 'Civil General District Hospital',
      organizationType: 'Hospital',
      serviceId: 'SRV-103',
      serviceName: 'Hospital & Healthcare Security',
      securityGuards: 6,
      supervisors: 2,
      housekeepingStaff: 4,
      totalStaff: 12,
      shift: 'Rotational',
      startDate: '2026-10-10',
      duration: '12 Months',
      workingDays: '24/7 Continuous',
      contactPerson: 'Dr. Meenakshi Iyer',
      email: 'civilhosp.admin@healthgov.in',
      phone: '9845098765',
      address: 'Main Health City Complex, MG Road',
      specialInstructions: 'Emergency OPD requires strict 24-hr guard deployment.',
      status: 'Approved',
      requestDate: '2026-09-24'
    },
    {
      id: 'REQ-2026-1004',
      organizationName: 'Municipal Corporation Head Office',
      organizationType: 'Government Office',
      serviceId: 'SRV-202',
      serviceName: 'Government Office Deep Cleaning & Support',
      securityGuards: 2,
      supervisors: 0,
      housekeepingStaff: 3,
      totalStaff: 5,
      shift: 'Morning',
      startDate: '2026-10-15',
      duration: '6 Months',
      workingDays: 'Monday to Friday',
      contactPerson: 'Sunita Patil',
      email: 'mc.headoffice@gov.in',
      phone: '9833445566',
      address: 'Central Civic Tower, Ambedkar Chowk',
      specialInstructions: 'Special care needed for council meeting halls.',
      status: 'Pending',
      requestDate: '2026-09-26'
    },
    {
      id: 'REQ-2026-1005',
      organizationName: 'Precision Auto-Tech Industrial Plant',
      organizationType: 'Factory',
      serviceId: 'SRV-104',
      serviceName: 'Factory & Industrial Security',
      securityGuards: 5,
      supervisors: 1,
      housekeepingStaff: 4,
      totalStaff: 10,
      shift: 'Rotational',
      startDate: '2026-11-01',
      duration: '12 Months',
      workingDays: 'All 7 Days',
      contactPerson: 'Harish Rao',
      email: 'h.rao@precisionautotech.com',
      phone: '9870192837',
      address: 'MIDC Industrial Sector, Plot 42-A',
      specialInstructions: 'Heavy vehicle inspection and weighment records required.',
      status: 'Under Review',
      requestDate: '2026-09-27'
    }
  ],

  // Staff Assignments
  assignments: [
    {
      assignmentId: 'ASG-2026-301',
      organizationId: 'ORG-1001',
      organizationName: 'Government Higher Secondary School',
      serviceName: 'School Security Guard Service',
      staffId: 'SEC-101',
      staffName: 'Ramesh Kumar',
      staffType: 'Security',
      designation: 'Senior Security Guard',
      shift: 'Morning',
      startDate: '2026-10-01',
      status: 'Active',
      assignedDate: '2026-09-25'
    },
    {
      assignmentId: 'ASG-2026-302',
      organizationId: 'ORG-1001',
      organizationName: 'Government Higher Secondary School',
      serviceName: 'Institutional Housekeeping & Cleaning',
      staffId: 'HK-204',
      staffName: 'Anita Kamble',
      staffType: 'Housekeeping',
      designation: 'School Cleaning Staff',
      shift: 'Morning',
      startDate: '2026-10-01',
      status: 'Active',
      assignedDate: '2026-09-25'
    },
    {
      assignmentId: 'ASG-2026-303',
      organizationId: 'ORG-1002',
      organizationName: 'District Collectorate & Revenue Complex',
      serviceName: 'Government Office Security',
      staffId: 'SEC-102',
      staffName: 'Mahendra Pratap Singh',
      staffType: 'Security',
      designation: 'Security Supervisor',
      shift: 'Morning',
      startDate: '2026-10-05',
      status: 'Active',
      assignedDate: '2026-09-25'
    },
    {
      assignmentId: 'ASG-2026-304',
      organizationId: 'ORG-1003',
      organizationName: 'Civil General District Hospital',
      serviceName: 'Hospital Clinical Sanitation & Waste Management',
      staffId: 'HK-201',
      staffName: 'Sunita Sharma',
      staffType: 'Housekeeping',
      designation: 'Cleaning Supervisor',
      shift: 'Morning',
      startDate: '2026-10-10',
      status: 'Active',
      assignedDate: '2026-09-26'
    }
  ],

  // Staff Daily Attendance Records
  attendance: [
    {
      id: 'ATT-2026-901',
      date: '2026-09-27',
      staffId: 'SEC-101',
      staffName: 'Ramesh Kumar',
      staffType: 'Security',
      organizationName: 'Government Higher Secondary School',
      checkIn: '07:25 AM',
      checkOut: '03:30 PM',
      status: 'Present',
      remarks: 'On time, immaculate uniform'
    },
    {
      id: 'ATT-2026-902',
      date: '2026-09-27',
      staffId: 'SEC-102',
      staffName: 'Mahendra Pratap Singh',
      staffType: 'Security',
      organizationName: 'District Collectorate & Revenue Complex',
      checkIn: '07:45 AM',
      checkOut: '04:00 PM',
      status: 'Present',
      remarks: 'Conducted shift briefing'
    },
    {
      id: 'ATT-2026-903',
      date: '2026-09-27',
      staffId: 'SEC-103',
      staffName: 'Vikram Jadhav',
      staffType: 'Security',
      organizationName: 'Civil General District Hospital',
      checkIn: '07:50 AM',
      checkOut: '04:00 PM',
      status: 'Present',
      remarks: 'Stationed at Emergency Gate'
    },
    {
      id: 'ATT-2026-904',
      date: '2026-09-27',
      staffId: 'SEC-104',
      staffName: 'Ajay Verma',
      staffType: 'Security',
      organizationName: 'District Collectorate & Revenue Complex',
      checkIn: '--:--',
      checkOut: '--:--',
      status: 'Leave',
      remarks: 'Approved medical leave'
    },
    {
      id: 'ATT-2026-905',
      date: '2026-09-27',
      staffId: 'HK-201',
      staffName: 'Sunita Sharma',
      staffType: 'Housekeeping',
      organizationName: 'Civil General District Hospital',
      checkIn: '06:55 AM',
      checkOut: '03:15 PM',
      status: 'Present',
      remarks: 'OT sanitation completed'
    },
    {
      id: 'ATT-2026-906',
      date: '2026-09-27',
      staffId: 'HK-202',
      staffName: 'Rekha Devi',
      staffType: 'Housekeeping',
      organizationName: 'Civil General District Hospital',
      checkIn: '07:05 AM',
      checkOut: '03:30 PM',
      status: 'Present',
      remarks: 'Bio-waste protocol followed'
    },
    {
      id: 'ATT-2026-907',
      date: '2026-09-27',
      staffId: 'HK-204',
      staffName: 'Anita Kamble',
      staffType: 'Housekeeping',
      organizationName: 'Government Higher Secondary School',
      checkIn: '07:15 AM',
      checkOut: '03:00 PM',
      status: 'Present',
      remarks: 'Pre-class sanitization done'
    },
    {
      id: 'ATT-2026-908',
      date: '2026-09-27',
      staffId: 'HK-203',
      staffName: 'Govind Narang',
      staffType: 'Housekeeping',
      organizationName: 'District Collectorate & Revenue Complex',
      checkIn: '--:--',
      checkOut: '--:--',
      status: 'Absent',
      remarks: 'Informed sick via phone'
    }
  ],

  // Customer Contact Enquiries
  enquiries: [
    {
      id: 'ENQ-2026-501',
      customerName: 'Dr. Rajesh Sen',
      email: 'principal.ghss@gov.in',
      phone: '9876543210',
      organization: 'Government Higher Secondary School',
      service: 'School Security',
      message: 'Need additional 2 night security guards during upcoming CBSE board examination period starting next month.',
      date: '2026-09-25',
      status: 'Responded',
      adminResponse: 'We have reserved 2 certified guards for your night examination schedule. Official roster sent to your email.'
    },
    {
      id: 'ENQ-2026-502',
      customerName: 'Sunita Patil',
      email: 'mc.headoffice@gov.in',
      phone: '9833445566',
      organization: 'Municipal Corporation Head Office',
      service: 'Government Office Deep Cleaning',
      message: 'Request quotation for mechanized floor scrubbers and ride-on vacuum machines along with daily housekeeping staff.',
      date: '2026-09-27',
      status: 'New',
      adminResponse: null
    },
    {
      id: 'ENQ-2026-503',
      customerName: 'Harish Rao',
      email: 'h.rao@precisionautotech.com',
      phone: '9870192837',
      organization: 'Precision Auto-Tech Industrial Plant',
      service: 'Factory Security',
      message: 'Please send supervisor Balram Pandey for site assessment of perimeter fence and gate 2 weighbridge.',
      date: '2026-09-26',
      status: 'In Progress',
      adminResponse: 'Site inspection scheduled for Monday 10:00 AM.'
    }
  ],

  // System Notifications
  notifications: [
    {
      id: 'NOTIF-1',
      title: 'New Service Request',
      message: 'REQ-2026-1005 received from Precision Auto-Tech Plant (10 Staff).',
      time: '10 mins ago',
      type: 'info',
      read: false
    },
    {
      id: 'NOTIF-2',
      title: 'Staff Assignment Completed',
      message: 'Guard Ramesh Kumar assigned to Govt Higher Secondary School.',
      time: '2 hours ago',
      type: 'success',
      read: false
    },
    {
      id: 'NOTIF-3',
      title: 'Daily Attendance Report',
      message: 'Morning shift attendance verified. 87.5% workforce present.',
      time: '4 hours ago',
      type: 'warning',
      read: true
    }
  ]
};
